name: Deploy Backend to Fly.io

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install deps (prod + build)
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "${HOME}/.fly/bin" >> $GITHUB_PATH

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if ! command -v fly >/dev/null; then echo "Fly CLI no instalado"; exit 1; fi
          sed -i "s/REEMPLAZA_CON_NOMBRE_APP_FLY/${{ secrets.FLY_APP_NAME }}/" fly.toml
          fly deploy --config fly.toml --remote-only --strategy immediate

      - name: Post URL
        if: always()
        run: |
          echo "App: ${{ secrets.FLY_APP_NAME }}"
          echo "https://${{ secrets.FLY_APP_NAME }}.fly.dev" || true